### ISSUE TITLE
I got stuck when I install it with pecl command.

### ISSUE THREAD

**Issue by xiangjihan** [reeze/php-leveldb#10]
Both on Fedora 19 x86 and CentOS 6.4 x86_64(vm).
I use the command "# pecl install leveldb"
And all the dependences has been installed.
![qq20131025090755](https://f.cloud.github.com/assets/3070542/1404856/efe877b8-3d11-11e3-8e1b-f63e6ecb2dfe.jpg)
I donot know the reason.
what should I do ?

**Comment by reeze** [comment]
If you encounter this problem reopen it please.
