### ISSUE TITLE
Fix documentation on home page easily

### ISSUE THREAD

**Issue by rjonesx** [reeze/php-leveldb#15]
You should switch the section below in the Readme to instead do...

git clone https://github.com/google/leveldb.git
cd leveldb
make

====== OLD BELOW ======
You could get leveldb from: http://code.google.com/p/leveldb/

$ wget http://leveldb.googlecode.com/files/leveldb-1.12.0.tar.gz
$ tar zxvf leveldb-1.12.0.tar.gz
$ cd leveldb-1.12.0
$ make
NOTE LevelDB didn't have make install target in Makefile: http://code.google.com/p/leveldb/issues/detail?id=27， If you want to install to a specific dir, you could: make INSTALL_PATH=/Your/Path/

**Comment by reeze** [comment]
fixed thank you.
