### ISSUE TITLE
Configure: error: Please reinstall the leveldb distribution

### ISSUE THREAD

**Issue by rjonesx** [reeze/php-leveldb#16]
I executed the following commands

cd /usr/local
git clone https://github.com/google/leveldb.git
cd leveldb
make
pecl install leveldb channel://pecl.php.net/leveldb-0.1.4

And I get the following error:
checking for leveldb location... search leveldb in yes
search leveldb in /usr/local
search leveldb in /usr
leveldb not found
configure: error: Please reinstall the leveldb distribution
ERROR: `/var/tmp/leveldb/configure' failed

I am using CentOS and I havent successfully been able to get leveldb to install because of this.

**Comment by 2072** [comment]
I am having the same problem on Debian 8 (Jessie) just because `leveldblib` is located in `/usr/lib/x86_64-linux-gnu/` instead of `/usr/lib/`

**Comment by reeze** [comment]
Now you guys should be able to install it now.  

pecl install leveldb channel://pecl.php.net/leveldb-0.1.5

**Comment by 52fhy** [comment]
```
cp -r /opt/leveldb-1.20/include/leveldb /usr/include/
./configure --with-leveldb=/opt/leveldb-1.20/out-shared/
```
