### ISSUE TITLE
configure failed 

### ISSUE THREAD

**Issue by jasonhe88** [reeze/php-leveldb#26]
CentOS: 7
PHP: 7.0.12
leveldb: 1.19

run following command:

$ ./configure --with-leveldb=/path/to/leveldb

get following error:

checking for leveldb support... yes, shared
checking for leveldb location... leveldb headers found in /home/jasonhe/pkgs/leveldb-1.19
find --/home/jasonhe/pkgs/leveldb-1.19/lib/x86_64-linux-gnu
find --/home/jasonhe/pkgs/leveldb-1.19/lib/x86_64-linux-gnu
find --/usr/local/lib/x86_64-linux-gnu
find --/usr/local/lib/x86_64-linux-gnu
find --/usr/lib/x86_64-linux-gnu
find --/usr/lib/x86_64-linux-gnu
leveldb not found
configure: error: Please reinstall the leveldb distribution
$
$

**Comment by reeze** [comment]
Did you compile  leveldb before configure?

**Comment by jasonhe88** [comment]
thank you for your reply :-)

yes, I compiled leveldb by running make command, then tried to install php-leveldb.

**Comment by jasonhe88** [comment]
I found what's the problem.

leveldb 1.19 changed the location of compiled library.

leveldb.so libraries are not in the leveldb home directory any more. instead, there are two new directories named out-static and out-shared which hold those library.

jason

**Comment by 52fhy** [comment]
> I found what's the problem.
> 
> leveldb 1.19 changed the location of compiled library.
> 
> leveldb.so libraries are not in the leveldb home directory any more. instead, there are two new directories named out-static and out-shared which hold those library.
> 
> jason
```
./configure --with-leveldb=/mnt/opt/leveldb-1.20/out-shared/
```
