### ISSUE TITLE
PHP 7 Compiling Error

### ISSUE THREAD

**Issue by benwelch** [reeze/php-leveldb#30]
I know that this could be a duplicate but I found an issue where @reeze said that he would add php 7 support soon. That was two years ago! This isn't soon. I'm kind of hoping that this is a different issue. I've been told to compile the php-leveldb bindings with my php multiple times and all I've found are these instructions which I followed: [https://github.com/reeze/php-leveldb](https://github.com/reeze/php-leveldb). All I want to do is use mcpe leveldb world in pocketmine. This is the error I got:
Makefile:194: recipe for target 'leveldb.lo' failed
make: *** [leveldb.lo] Error 1

**Comment by reeze** [comment]
try latest master please.
