### ISSUE TITLE
leveldb triggers asserts when using `leveldb_close()` on a DB that has an open iterator associated with it

### ISSUE THREAD

**Issue by dktapps** [reeze/php-leveldb#36]
[This assert](https://github.com/google/leveldb/blob/04470825ac96cab0d9d16e4ed410349d082fbf82/db/version_set.cc#L799) is triggered when `LevelDB->close()` is called on a DB which has an open iterator attached to it. This causes several test failures when leveldb is compiled in debug mode.

These asserts can be avoided by calling `LevelDBIterator->destroy()` prior to the `LevelDB` object that it is associated with going out of scope, but this should preferably be handled by the extension automatically instead.

**Comment by remicollet** [comment]
+1

Lot of work needed to fix this in the extension side

IMHO, better to drop low level method (close) and rely on common destructor behavior.
Then raise count on the DB object when an Iterator / Snapshot is created, and decrease when removed
Thus this will ensure the DB is close after all other related objects.

**Comment by remicollet** [comment]
See PR #41
