### ISSUE TITLE
API Docs Offline, Looking For Read-Only DB Open Params

### ISSUE THREAD

**Issue by taoteh1221** [reeze/php-leveldb#37]
The API docs at http://reeze.cn/php-leveldb/doc/ are offline, so I figured I'd post an issue here. I'm building a blockchain block explorer ( https://github.com/taoteh1221/Zillexplorer ), and need to assure I only open php-leveldb's connection to the blockchain database as read-only to avoid data corruption. What are the parameters I should be using to achieve this?

**Comment by dktapps** [comment]
Most of the API is documented in the readme. You can also look at https://github.com/reeze/php-leveldb/blob/master/stub.php for API reference.

To get a read only view of a DB you probably want a LevelDBSnapshot.

**Comment by taoteh1221** [comment]
Thanks. I just saw the snapshot documentation further down in the readme as well.
