### ISSUE TITLE
Segmentaion fault when using LevelDBIterator

### ISSUE THREAD

**Issue by andkom** [reeze/php-leveldb#38]
1) I get segmentation fault error at the end of script when using LevelDBIterator object.

sample code:

```php
$db = new \LevelDB($path);
$it = new \LevelDBIterator($db);
echo "OK\n";
```
will output:

```
OK
Segmentation fault
```

while the following code work with no issues:

```php
$db = new \LevelDB($path);
$it = $db->getIterator();
echo "OK\n";
```
2) Sometimes when iterating an iterator, it will seg fault after the last item.
second run will produce error:

```
pthread lock: Invalid argument
Aborted
```
3) On Mac OS i get segmentation fault error after every php command run, even without script.
For example running just php -v shows seg fault when extension leveldb.so is loaded.
Disabling the extension will fix seg fault error.

OS tested: ubuntu (docker), debian (docker), macos
PHP versions tested: 7.2.7, 7.2.9
leveldb versions tested: 1.20, latest from github
php-leveldb versions tested: 0.2.1, latest from pecl, latest from github.

**Comment by dktapps** [comment]
On Ubuntu 18.04, with PHP 7.2.11-dev NTS, latest master of php-leveldb and leveldb 1.20, I am not able to reproduce this issue. I also tested MacOS and Ubuntu with ZTS 7.2.9 and no issues showed themselves. We may need more information to get to the bottom of this.

**Comment by andkom** [comment]
I did some tests and figured out that DB read will fail only when enclosed in a function or class method.

```php
function read_db_fail()
{
    $db = new \LevelDB('/path/to/db');
    $it = new \LevelDBIterator($db);

    $c = 0;

    foreach ($it as $key => $value) {
        $c++;
    }

    echo "count: $c\n";

    $db->close();
}
```
the above function will output on an existing db:

```
count: XXX
Segmentation fault
```
when opening a new db it will output:

```
count: 0
pthread lock: Invalid argument
Aborted
```

the following function will also fail:

```php
function read_db_fail_2()
{
    $db = new \LevelDB('./test');
    $it = $db->getIterator();

    $c = 0;

    foreach ($it as $key => $value) {
        $c++;
    }

    echo "count: $c\n";

    $db->close();
}
```

the only working function is:

```php
function read_db()
{
    $db = new \LevelDB('./test');

    $c = 0;

    foreach ($db->getIterator() as $key => $value) {
        $c++;
    }

    echo "count: $c\n";

    $db->close();
}
```
i've shared docker container: doczxc/leveldb-test where you can do some tests.

**Comment by dktapps** [comment]
Both of your test samples trigger the following assert for me (on Windows): 
```
Assertion failed: dummy_versions_.next_ == &dummy_versions_, file c:\pocketmine-php-sdk\deps\leveldb\db\version_set.cc, line 798
```
It would appear, then, that this is directly related to #36 . I was under the impression that this assert was harmless, but it appears not.

**Comment by bynicolas** [comment]
Don't know if I should open another issue, but point 3 in op issue is still a thing. Every php command returns a `Segmentation fault: 11` error when `leveldb.so` is loaded.

**Comment by dktapps** [comment]
Yes, this hasn't been addressed yet.
