### ISSUE TITLE
Prepare a 0.3.0 release

### ISSUE THREAD

**Issue by dktapps** [reeze/php-leveldb#44]
Changes worthy of note since 0.2.1:

- fixed assert failures and possible faults involving comparators (f858b3ea2b605c3aa3d61d2079401ae8b98a46b5)
- add support for PHP 7.3, 7.4 and 8.0
- deprecate `LevelDB->close()` (use `unset($db)` instead, allows more consistent behaviour of iterators and snapshots, and fixes leveldb asserts) (
- fix wrong arginfo of `LevelDBWriteBatch`
- fix memory errors when google/leveldb was compiled with different compiler options than php-leveldb

@reeze I don't have maintainer access on PECL, could you tag the release and upload it (or add me as a maintainer so I can do it)?

**Comment by reeze** [comment]
Hi @dktapps  you have been assigned as the lead of the leveldb package on PECL :)

**Comment by dktapps** [comment]
Awesome, thank you!

**Comment by dktapps** [comment]
Released and tagged.
