### ISSUE TITLE
Configuration error.

### ISSUE THREAD

**Issue by akDeveloper** [reeze/php-leveldb#6]
I had some issues when i tried to compile php-leveldb extension in an Arch Linux box.
Here is a the list of [Archlinux](https://www.archlinux.org/packages/extra/x86_64/leveldb/files/) distribtion files.

When i tried to configure the lib with 
`./configure --with-leveldb=/usr/include/leveldb`
i was getting the error:

```
checking for leveldb files in default path... not found
configure: error: Please reinstall the leveldb distribution
```

Looking at `config.m4` file at line 20, there is no chance this to return true since it searches for `include/leveldb/c.h`(found it correctly) but fails in `libleveldb.a` because it is located at `/usr/lib` folder. So cannot be found at `/usr/local` or `/usr` folders.

Changing the line 14 from `SEARCH_LIB="libleveldb.a"` to `SEARCH_LIB="lib/libleveldb.a"` worked for my situation, but i don't know if it is the correct answer since it must be tested to other machines too.

**Comment by hjhstanley** [comment]
i met the same mistake when i am using leveldb-v1.19, my solution is "sudo cp leveldb-1.19/out-shared/libleveldb.so* /usr/lib/"
