### ISSUE TITLE
failed test (v 0.1.4 + leveldb 1.13)

### ISSUE THREAD

**Issue by remicollet** [reeze/php-leveldb#9]
=====================================================================
     FAILED TEST SUMMARY
     ---------------------------------------------------------------------
     leveldb - custom comparator [tests/009-comparator.phpt]
     =====================================================================

     $ diff -u tests/009-comparator.exp tests/009-comparator.out
     --- tests/009-comparator.exp	2013-08-25 09:18:26.655194065 +0200
     +++ tests/009-comparator.out	2013-08-25 09:18:26.655194065 +0200
     @@ -1,15 +1,4 @@
      *** could not use invalid custom comparator ***
      Invalid open option: comparator, invaid_func() is not callable
      *** valid custom comparator ***
     -6
     -5
     -4
     -3
     -2
     -1
     -*** custom comparator can only open with the same comparator again ***
     -Invalid argument: php_leveldb.custom_comparator%s leveldb.BytewiseComparator
     -bool(true)
     -*** custom comparator which throw exception ***
     -Oops!
     -==DONE==
     +6

**Comment by reeze** [comment]
Thanks @remicollet  
:(.   I couldn't reproduce it.  reopen it please if the problem still exist
